FROM openjdk:8-jre-alpine3.9
FROM maven:3.5.2
WORKDIR /docker-app
ADD . /docker-app
CMD ["mvn", "clean install"]

COPY target/myspring-boot-0.0.1-SNAPSHOT.jar myspring-boot-1.0.0.jar

EXPOSE 8080
CMD ["java","-jar","./myspring-boot-1.0.0.jar"]
